 * Running on http://0.0.0.0:8834/
 * Restarting with reloader
58.1.228.208 - - [13/Jul/2012 10:30:19] "GET /ec2/ HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:30:19] "GET /static/inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 10:30:19] "GET /static/igloos.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 10:30:19] "GET /static/style.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 10:30:19] "GET /static/grid.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 10:30:19] "GET /static/breadcrumb.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 10:30:20] "GET /static/img/page-top.gif HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 10:32:36] "GET /ec2/ap-northeast-1 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1701, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1689, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/asato/Dropbox/MyProjects/flaws/__init__.py", line 35, in ec2Region
    } for instance in r.instances]
AttributeError: 'ResultSet' object has no attribute 'instances'
58.1.228.208 - - [13/Jul/2012 10:32:36] "GET /ec2/ap-northeast-1?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:32:36] "GET /ec2/ap-northeast-1?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:32:36] "GET /ec2/ap-northeast-1?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:32:36] "GET /ec2/ap-northeast-1?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:32:36] "GET /ec2/ap-northeast-1?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:32:36] "GET /ec2/ap-northeast-1?__debugger__=yes&cmd=resource&f=source.png HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:32:36] "GET /favicon.ico HTTP/1.1" 404 -
58.1.228.208 - - [13/Jul/2012 10:32:45] "GET /favicon.ico HTTP/1.1" 404 -
58.1.228.208 - - [13/Jul/2012 10:32:48] "GET /ec2/ HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:32:48] "GET /static/inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 10:32:48] "GET /static/igloos.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 10:32:48] "GET /static/style.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 10:32:48] "GET /static/grid.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 10:32:48] "GET /static/breadcrumb.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 10:32:48] "GET /static/icon.png HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:32:51] "GET /ec2/ap-northeast-1 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1701, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1689, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/asato/Dropbox/MyProjects/flaws/__init__.py", line 35, in ec2Region
    } for instance in r.instances]
AttributeError: 'ResultSet' object has no attribute 'instances'
58.1.228.208 - - [13/Jul/2012 10:32:51] "GET /ec2/ap-northeast-1?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:32:51] "GET /ec2/ap-northeast-1?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:32:51] "GET /ec2/ap-northeast-1?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:32:51] "GET /ec2/ap-northeast-1?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:32:51] "GET /ec2/ap-northeast-1?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:32:51] "GET /ec2/ap-northeast-1?__debugger__=yes&cmd=resource&f=source.png HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:32:51] "GET /favicon.ico HTTP/1.1" 404 -
 * Detected change in '__init__.py', reloading
 * Restarting with reloader
58.1.228.208 - - [13/Jul/2012 10:37:14] "GET /ec2/ HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:37:14] "GET /static/inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 10:37:14] "GET /static/igloos.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 10:37:14] "GET /static/style.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 10:37:14] "GET /static/grid.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 10:37:14] "GET /static/breadcrumb.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 10:37:16] "GET /ec2/ap-northeast-1 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1701, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1689, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/asato/Dropbox/MyProjects/flaws/__init__.py", line 35, in ec2Region
    } for instance in i.instances for i in r]
UnboundLocalError: local variable 'i' referenced before assignment
58.1.228.208 - - [13/Jul/2012 10:37:16] "GET /ec2/ap-northeast-1?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:37:16] "GET /ec2/ap-northeast-1?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:37:16] "GET /ec2/ap-northeast-1?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:37:16] "GET /ec2/ap-northeast-1?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:37:16] "GET /ec2/ap-northeast-1?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:37:16] "GET /ec2/ap-northeast-1?__debugger__=yes&cmd=resource&f=source.png HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:37:16] "GET /favicon.ico HTTP/1.1" 404 -
58.1.228.208 - - [13/Jul/2012 10:37:51] "GET /ec2/ap-northeast-1 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1701, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1689, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/asato/Dropbox/MyProjects/flaws/__init__.py", line 35, in ec2Region
    } for instance in i.instances for i in r]
UnboundLocalError: local variable 'i' referenced before assignment
58.1.228.208 - - [13/Jul/2012 10:37:51] "GET /ec2/ap-northeast-1?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:37:51] "GET /ec2/ap-northeast-1?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:37:51] "GET /ec2/ap-northeast-1?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:37:52] "GET /ec2/ap-northeast-1?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:37:52] "GET /ec2/ap-northeast-1?__debugger__=yes&cmd=resource&f=source.png HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:37:52] "GET /ec2/ap-northeast-1?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:37:52] "GET /favicon.ico HTTP/1.1" 404 -
 * Detected change in '__init__.py', reloading
 * Restarting with reloader
58.1.228.208 - - [13/Jul/2012 10:39:18] "GET /ec2/ap-northeast-1 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1701, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1689, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/asato/Dropbox/MyProjects/flaws/__init__.py", line 37, in ec2Region
    } for instance in i.instances for i in r ]
UnboundLocalError: local variable 'i' referenced before assignment
58.1.228.208 - - [13/Jul/2012 10:39:18] "GET /ec2/ap-northeast-1?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:39:18] "GET /ec2/ap-northeast-1?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:39:18] "GET /ec2/ap-northeast-1?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:39:18] "GET /ec2/ap-northeast-1?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:39:18] "GET /ec2/ap-northeast-1?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:39:18] "GET /ec2/ap-northeast-1?__debugger__=yes&cmd=resource&f=source.png HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:39:18] "GET /favicon.ico HTTP/1.1" 404 -
 * Running on http://0.0.0.0:8834/
 * Restarting with reloader
58.1.228.208 - - [13/Jul/2012 10:40:00] "GET /ec2/ap-northeast-1 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1701, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1689, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/asato/Dropbox/MyProjects/flaws/__init__.py", line 37, in ec2Region
    } for instance in i.instances for i in r ]
UnboundLocalError: local variable 'i' referenced before assignment
58.1.228.208 - - [13/Jul/2012 10:40:01] "GET /ec2/ap-northeast-1?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:40:01] "GET /ec2/ap-northeast-1?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:40:01] "GET /ec2/ap-northeast-1?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:40:01] "GET /ec2/ap-northeast-1?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:40:01] "GET /ec2/ap-northeast-1?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:40:01] "GET /ec2/ap-northeast-1?__debugger__=yes&cmd=resource&f=source.png HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:40:01] "GET /favicon.ico HTTP/1.1" 404 -
58.1.228.208 - - [13/Jul/2012 10:40:03] "GET /ec2/ap-northeast-1 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1701, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1689, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/asato/Dropbox/MyProjects/flaws/__init__.py", line 37, in ec2Region
    } for instance in i.instances for i in r ]
UnboundLocalError: local variable 'i' referenced before assignment
58.1.228.208 - - [13/Jul/2012 10:40:04] "GET /ec2/ap-northeast-1?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:40:04] "GET /ec2/ap-northeast-1?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:40:04] "GET /ec2/ap-northeast-1?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:40:04] "GET /ec2/ap-northeast-1?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:40:04] "GET /ec2/ap-northeast-1?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:40:04] "GET /ec2/ap-northeast-1?__debugger__=yes&cmd=resource&f=source.png HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 10:40:04] "GET /favicon.ico HTTP/1.1" 404 -
 * Running on http://0.0.0.0:8834/
 * Restarting with reloader
58.1.228.208 - - [13/Jul/2012 11:09:19] "GET /r53 HTTP/1.1" 301 -
58.1.228.208 - - [13/Jul/2012 11:09:19] "GET /r53/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1701, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1689, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/asato/Dropbox/MyProjects/flaws/__init__.py", line 62, in Route53
    con = boto.connect_route53()
NameError: global name 'boto' is not defined
58.1.228.208 - - [13/Jul/2012 11:09:19] "GET /r53/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 11:09:19] "GET /r53/?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 11:09:19] "GET /r53/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 11:09:19] "GET /r53/?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 11:09:20] "GET /r53/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 11:09:20] "GET /r53/?__debugger__=yes&cmd=resource&f=source.png HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 11:09:20] "GET /favicon.ico HTTP/1.1" 404 -
 * Detected change in '__init__.py', reloading
 * Restarting with reloader
58.1.228.208 - - [13/Jul/2012 11:09:53] "GET /r53/ HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 11:10:19] "GET /r53/ HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 11:10:19] "GET /static/inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:10:19] "GET /static/igloos.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:10:19] "GET /static/style.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:10:19] "GET /static/grid.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:10:19] "GET /static/breadcrumb.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:10:25] "GET /r53/ HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 11:10:25] "GET /static/inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:10:25] "GET /static/igloos.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:10:25] "GET /static/style.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:10:25] "GET /static/grid.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:10:25] "GET /static/breadcrumb.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:10:27] "GET /r53/ HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 11:10:29] "GET / HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 11:10:31] "GET /ec2 HTTP/1.1" 301 -
58.1.228.208 - - [13/Jul/2012 11:10:31] "GET /ec2/ HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 11:10:34] "GET /r53/ HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 11:12:40] "GET /r53/ HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 11:12:40] "GET /static/inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:12:40] "GET /static/igloos.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:12:40] "GET /static/style.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:12:40] "GET /static/grid.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:12:40] "GET /static/breadcrumb.inuit.css HTTP/1.1" 304 -
 * Running on http://0.0.0.0:8834/
 * Restarting with reloader
58.1.228.208 - - [13/Jul/2012 11:13:06] "GET /r53/ HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 11:13:06] "GET /static/inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:13:06] "GET /static/igloos.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:13:06] "GET /static/style.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:13:06] "GET /static/grid.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:13:06] "GET /static/breadcrumb.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:13:11] "GET /r53/Z3UCRU4TMS84Q3 HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 11:17:49] "GET /r53/ HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 11:17:49] "GET /static/inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:17:49] "GET /static/igloos.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:17:49] "GET /static/style.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:17:49] "GET /static/grid.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:17:49] "GET /static/breadcrumb.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:17:53] "GET /r53/Z3UCRU4TMS84Q3 HTTP/1.1" 200 -
 * Detected change in '__init__.py', reloading
Unhandled exception in thread started by 
sys.excepthook is missing
lost sys.stderr
 * Restarting with reloader
 * Detected change in '__init__.py', reloading
 * Restarting with reloader
 * Detected change in '__init__.py', reloading
Unhandled exception in thread started by 
sys.excepthook is missing
lost sys.stderr
 * Restarting with reloader
 * Detected change in '__init__.py', reloading
 * Restarting with reloader
58.1.228.208 - - [13/Jul/2012 11:32:28] "GET /r53/ HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 11:32:32] "GET /iam/user HTTP/1.1" 301 -
58.1.228.208 - - [13/Jul/2012 11:32:33] "GET /iam/user/ HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 11:32:42] "GET /iam/ HTTP/1.1" 404 -
58.1.228.208 - - [13/Jul/2012 11:32:42] "GET /favicon.ico HTTP/1.1" 404 -
58.1.228.208 - - [13/Jul/2012 11:32:46] "GET /iam/user/ HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 11:33:10] "GET /iam/user/ HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 11:33:10] "GET /static/inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:33:10] "GET /static/igloos.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:33:10] "GET /static/style.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:33:10] "GET /static/grid.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:33:10] "GET /static/breadcrumb.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:35:11] "GET /iam/user/ HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 11:35:11] "GET /static/inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:35:11] "GET /static/igloos.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:35:11] "GET /static/style.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:35:11] "GET /static/grid.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:35:11] "GET /static/breadcrumb.inuit.css HTTP/1.1" 304 -
 * Detected change in '__init__.py', reloading
 * Restarting with reloader
58.1.228.208 - - [13/Jul/2012 11:40:24] "GET /iam/user/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1701, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1689, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/asato/Dropbox/MyProjects/flaws/__init__.py", line 133, in IamUser
    'id': users.user_id,
AttributeError: 'ListElement' object has no attribute 'user_id'
58.1.228.208 - - [13/Jul/2012 11:40:24] "GET /iam/user/?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 11:40:24] "GET /iam/user/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 11:40:24] "GET /iam/user/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 11:40:24] "GET /iam/user/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 11:40:24] "GET /iam/user/?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 11:40:24] "GET /iam/user/?__debugger__=yes&cmd=resource&f=source.png HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 11:40:24] "GET /favicon.ico HTTP/1.1" 404 -
 * Detected change in '__init__.py', reloading
Unhandled exception in thread started by 
sys.excepthook is missing
lost sys.stderr
 * Restarting with reloader
58.1.228.208 - - [13/Jul/2012 11:41:54] "GET /iam/user/ HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 11:41:54] "GET /static/inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:41:54] "GET /static/igloos.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:41:54] "GET /static/style.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:41:54] "GET /static/grid.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:41:54] "GET /static/breadcrumb.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:43:51] "GET /iam/user/ HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 11:43:51] "GET /static/inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:43:51] "GET /static/igloos.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:43:51] "GET /static/style.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:43:51] "GET /static/grid.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:43:51] "GET /static/breadcrumb.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:44:52] "GET /iam/user/ HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 11:44:52] "GET /static/inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:44:52] "GET /static/igloos.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:44:52] "GET /static/style.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:44:52] "GET /static/grid.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:44:52] "GET /static/breadcrumb.inuit.css HTTP/1.1" 304 -
 * Detected change in '__init__.py', reloading
 * Restarting with reloader
58.1.228.208 - - [13/Jul/2012 11:46:33] "GET /iam/user/ HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 11:46:33] "GET /static/inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:46:33] "GET /static/igloos.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:46:33] "GET /static/style.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:46:33] "GET /static/grid.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:46:33] "GET /static/breadcrumb.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:46:40] "GET /iam/user/dalun.zhong HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 11:47:30] "GET /iam/user/ HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 11:47:30] "GET /static/inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:47:30] "GET /static/igloos.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:47:30] "GET /static/style.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:47:30] "GET /static/grid.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:47:30] "GET /static/breadcrumb.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:47:51] "GET /favicon.ico HTTP/1.1" 404 -
58.1.228.208 - - [13/Jul/2012 11:54:59] "GET /iam/user/ HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 11:54:59] "GET /static/inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:54:59] "GET /static/igloos.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:54:59] "GET /static/style.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:54:59] "GET /static/grid.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:54:59] "GET /static/breadcrumb.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 11:55:01] "GET /iam/user/azumi.wakuda HTTP/1.1" 200 -
 * Detected change in '__init__.py', reloading
 * Restarting with reloader
58.1.228.208 - - [13/Jul/2012 12:00:02] "GET /iam/user/azumi.wakuda HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 12:00:02] "GET /static/inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:00:02] "GET /static/igloos.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:00:02] "GET /static/style.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:00:02] "GET /static/grid.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:00:02] "GET /static/breadcrumb.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:11:40] "GET /iam/user/masaki.asato HTTP/1.1" 200 -
 * Detected change in '__init__.py', reloading
 * Restarting with reloader
58.1.228.208 - - [13/Jul/2012 12:23:31] "GET /iam/user/masaki.asato HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 12:23:31] "GET /static/inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:23:31] "GET /static/igloos.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:23:31] "GET /static/style.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:23:31] "GET /static/grid.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:23:31] "GET /static/breadcrumb.inuit.css HTTP/1.1" 304 -
 * Detected change in '__init__.py', reloading
 * Restarting with reloader
58.1.228.208 - - [13/Jul/2012 12:32:40] "GET /iam/user/masaki.asato HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1701, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1689, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/asato/Dropbox/MyProjects/flaws/__init__.py", line 155, in IamUser
    } for g in groups ]
  File "/usr/local/lib/python2.7/dist-packages/boto/jsonresponse.py", line 82, in __getattr__
    raise AttributeError
AttributeError
58.1.228.208 - - [13/Jul/2012 12:32:40] "GET /iam/user/masaki.asato?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 12:32:40] "GET /iam/user/masaki.asato?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 12:32:40] "GET /iam/user/masaki.asato?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 12:32:40] "GET /iam/user/masaki.asato?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 12:32:40] "GET /iam/user/masaki.asato?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 12:32:40] "GET /iam/user/masaki.asato?__debugger__=yes&cmd=resource&f=source.png HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 12:32:40] "GET /favicon.ico HTTP/1.1" 404 -
58.1.228.208 - - [13/Jul/2012 12:33:19] "GET /iam/user/masaki.asato?__debugger__=yes&cmd=source&frm=139894870208208&s=8LggVvbB5qLnmnXAL6J4 HTTP/1.1" 200 -
 * Detected change in '__init__.py', reloading
 * Restarting with reloader
58.1.228.208 - - [13/Jul/2012 12:33:31] "GET /iam/user/masaki.asato HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1701, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1689, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/asato/Dropbox/MyProjects/flaws/__init__.py", line 159, in IamUser
    return render_template('iam/UserView.html', user=user,group=group,ug=ug,up=up)
NameError: global name 'group' is not defined
58.1.228.208 - - [13/Jul/2012 12:33:32] "GET /favicon.ico HTTP/1.1" 404 -
 * Detected change in '__init__.py', reloading
Unhandled exception in thread started by 
sys.excepthook is missing
lost sys.stderr
 * Restarting with reloader
58.1.228.208 - - [13/Jul/2012 12:33:53] "GET /iam/user/masaki.asato HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 12:33:53] "GET /static/inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:33:53] "GET /static/igloos.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:33:53] "GET /static/style.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:33:53] "GET /static/grid.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:33:53] "GET /static/breadcrumb.inuit.css HTTP/1.1" 304 -
 * Detected change in '__init__.py', reloading
 * Restarting with reloader
58.1.228.208 - - [13/Jul/2012 12:34:41] "GET /iam/user/masaki.asato HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 12:34:41] "GET /static/inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:34:41] "GET /static/igloos.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:34:41] "GET /static/style.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:34:41] "GET /static/grid.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:34:41] "GET /static/breadcrumb.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:35:06] "GET /iam/user/masaki.asato HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 12:35:06] "GET /static/igloos.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:35:06] "GET /static/style.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:35:06] "GET /static/inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:35:06] "GET /static/grid.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:35:06] "GET /static/breadcrumb.inuit.css HTTP/1.1" 304 -
 * Detected change in '__init__.py', reloading
 * Restarting with reloader
58.1.228.208 - - [13/Jul/2012 12:36:07] "GET /iam/user/masaki.asato HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 12:36:07] "GET /static/inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:36:07] "GET /static/igloos.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:36:07] "GET /static/style.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:36:07] "GET /static/grid.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:36:07] "GET /static/breadcrumb.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:36:20] "GET /iam/user/masaki.asato HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 12:36:20] "GET /static/igloos.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:36:20] "GET /static/inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:36:20] "GET /static/style.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:36:20] "GET /static/grid.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:36:20] "GET /static/breadcrumb.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:36:34] "GET /iam/user/masaki.asato HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 12:36:34] "GET /static/inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:36:34] "GET /static/igloos.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:36:34] "GET /static/style.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:36:34] "GET /static/grid.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:36:34] "GET /static/breadcrumb.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:37:03] "GET /iam/user/masaki.asato HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 12:37:03] "GET /static/inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:37:03] "GET /static/igloos.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:37:03] "GET /static/style.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:37:03] "GET /static/grid.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:37:03] "GET /static/breadcrumb.inuit.css HTTP/1.1" 304 -
 * Detected change in '__init__.py', reloading
 * Restarting with reloader
58.1.228.208 - - [13/Jul/2012 12:43:24] "GET /iam/user/masaki.asato HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1701, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1689, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/asato/Dropbox/MyProjects/flaws/__init__.py", line 159, in IamUser
    policies = up['list_groups_for_user_response']['list_user_policies_result']
KeyError: 'list_groups_for_user_response'
58.1.228.208 - - [13/Jul/2012 12:43:24] "GET /iam/user/masaki.asato?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 12:43:24] "GET /iam/user/masaki.asato?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 12:43:24] "GET /iam/user/masaki.asato?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 12:43:24] "GET /iam/user/masaki.asato?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 12:43:24] "GET /iam/user/masaki.asato?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 12:43:24] "GET /iam/user/masaki.asato?__debugger__=yes&cmd=resource&f=source.png HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 12:43:24] "GET /favicon.ico HTTP/1.1" 404 -
 * Detected change in '__init__.py', reloading
Unhandled exception in thread started by 
sys.excepthook is missing
lost sys.stderr
 * Restarting with reloader
58.1.228.208 - - [13/Jul/2012 12:43:59] "GET /iam/user/masaki.asato HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1701, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1689, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/asato/Dropbox/MyProjects/flaws/__init__.py", line 159, in IamUser
    policies = up['list_policies_for_user_response']['list_user_policies_result']
KeyError: 'list_policies_for_user_response'
58.1.228.208 - - [13/Jul/2012 12:43:59] "GET /iam/user/masaki.asato?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 12:43:59] "GET /iam/user/masaki.asato?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 12:43:59] "GET /iam/user/masaki.asato?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 12:43:59] "GET /iam/user/masaki.asato?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 12:43:59] "GET /iam/user/masaki.asato?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 12:43:59] "GET /iam/user/masaki.asato?__debugger__=yes&cmd=resource&f=source.png HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 12:43:59] "GET /favicon.ico HTTP/1.1" 404 -
 * Detected change in '__init__.py', reloading
 * Restarting with reloader
58.1.228.208 - - [13/Jul/2012 12:44:40] "GET /iam/user/masaki.asato HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 12:44:40] "GET /static/inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:44:40] "GET /static/igloos.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:44:40] "GET /static/style.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:44:40] "GET /static/grid.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:44:40] "GET /static/breadcrumb.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:44:40] "GET /static/img/page-top.gif HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:45:04] "GET /iam/user/masaki.asato HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 12:45:04] "GET /static/inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:45:04] "GET /static/igloos.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:45:04] "GET /static/style.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:45:04] "GET /static/grid.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:45:04] "GET /static/breadcrumb.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:45:04] "GET /static/img/page-top.gif HTTP/1.1" 304 -
 * Detected change in '__init__.py', reloading
Unhandled exception in thread started by 
sys.excepthook is missing
lost sys.stderr
 * Restarting with reloader
58.1.228.208 - - [13/Jul/2012 12:46:24] "GET /iam/user/masaki.asato HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 12:46:24] "GET /static/inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:46:24] "GET /static/igloos.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:46:24] "GET /static/style.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:46:24] "GET /static/grid.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:46:24] "GET /static/breadcrumb.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:54:09] "GET /iam/user/masaki.asato HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 12:54:09] "GET /static/inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:54:09] "GET /static/igloos.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:54:09] "GET /static/style.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:54:09] "GET /static/grid.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:54:09] "GET /static/breadcrumb.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:54:52] "GET /iam/user/masaki.asato HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 12:54:52] "GET /static/inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:54:52] "GET /static/igloos.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:54:52] "GET /static/style.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:54:52] "GET /static/grid.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:54:52] "GET /static/breadcrumb.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:55:45] "GET /iam/user/masaki.asato HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 12:55:45] "GET /static/inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:55:45] "GET /static/igloos.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:55:45] "GET /static/style.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:55:45] "GET /static/grid.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:55:45] "GET /static/breadcrumb.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 12:58:14] "GET /iam/user/ HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 13:02:06] "GET /iam/user/azumi.wakuda HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 13:19:35] "GET /iam/user/ HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 13:19:35] "GET /static/inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 13:19:35] "GET /static/igloos.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 13:19:35] "GET /static/style.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 13:19:35] "GET /static/grid.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 13:19:35] "GET /static/breadcrumb.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 13:20:39] "GET /iam/user/ HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 13:20:39] "GET /static/inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 13:20:39] "GET /static/igloos.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 13:20:39] "GET /static/style.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 13:20:39] "GET /static/grid.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 13:20:39] "GET /static/breadcrumb.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 13:20:56] "GET /ec2/ HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 13:20:59] "GET /r53/ HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 13:21:01] "GET /iam/user/ HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 13:21:04] "GET /r53/ HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 13:23:33] "GET /r53/ HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 13:23:33] "GET /static/inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 13:23:33] "GET /static/igloos.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 13:23:33] "GET /static/style.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 13:23:33] "GET /static/grid.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 13:23:33] "GET /static/breadcrumb.inuit.css HTTP/1.1" 304 -
 * Detected change in '__init__.py', reloading
 * Restarting with reloader
58.1.228.208 - - [13/Jul/2012 13:24:41] "GET /r53/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1701, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1689, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/asato/Dropbox/MyProjects/flaws/__init__.py", line 85, in Route53
    return render_template('r53/ZoneIndex.html', hzl=hzl)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 124, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 758, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 719, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 693, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 493, in compile
    self.handle_exception(exc_info, source_hint=source)
  File "/home/asato/Dropbox/MyProjects/flaws/templates/r53/ZoneIndex.html", line 22, in template
    {% endif %}
TemplateSyntaxError: Encountered unknown tag 'endif'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
58.1.228.208 - - [13/Jul/2012 13:24:41] "GET /r53/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 13:24:41] "GET /r53/?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 13:24:41] "GET /r53/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 13:24:41] "GET /r53/?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 13:24:41] "GET /r53/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 13:24:41] "GET /r53/?__debugger__=yes&cmd=resource&f=source.png HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 13:24:41] "GET /favicon.ico HTTP/1.1" 404 -
58.1.228.208 - - [13/Jul/2012 13:24:59] "GET /r53/ HTTP/1.1" 200 -
58.1.228.208 - - [13/Jul/2012 13:25:00] "GET /static/inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 13:25:00] "GET /static/igloos.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 13:25:00] "GET /static/style.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 13:25:00] "GET /static/grid.inuit.css HTTP/1.1" 304 -
58.1.228.208 - - [13/Jul/2012 13:25:00] "GET /static/breadcrumb.inuit.css HTTP/1.1" 304 -
 * Detected change in '__init__.py', reloading
 * Restarting with reloader
58.1.228.208 - - [13/Jul/2012 13:30:39] "GET /r53/Z1PMCLJCWQXOK3 HTTP/1.1" 200 -
 * Detected change in '__init__.py', reloading
 * Restarting with reloader
